steps:
  # 1) Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/chatbot-predictivo:$SHORT_SHA',
        '.',
      ]

  # 2) Desplegar en Cloud Run (región us-central1 como ejemplo)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'chatbot-predictivo',
        '--image',
        'gcr.io/$PROJECT_ID/chatbot-predictivo:$SHORT_SHA',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
      ]
images:
  - 'gcr.io/$PROJECT_ID/chatbot-predictivo:$SHORT_SHA'
